config/routes.rb
Rails.application.routes.draw do

  resources :books
  
  resources :charges, only: [:new, :create]
  
  devise_for :users, :controllers => { 
    
    :registrations => "user/registrations"
  }
  
  root 'pages#home'
  
  get '/about' => 'pages#about'
  
  get '/privacy' => 'pages#privacy'
  
  get '/terms_and_conditions' => 'pages#terms'
  
  get '/cart'  => 'cart#index'
  
  get 'cart/clear' => 'cart#removeAll'
  
  get 'cart/remove/:id' => 'cart#remove'

  get 'cart/:id' => 'cart#add'
  

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  
  before_filter :ensure_not_admin
  
  #Check if the currently logged in user is not Admin
  #If so, an error will be returned as cart is not an Admin option.
  def ensure_not_admin
    
    if current_user && current_user.admin?
    
      render :text => "Admin, Admin... What are you doing?", :status => :unauthorized
      
    end
    
  end
  
  def index
    
    if session[:cart] then
      
      @cart = session[:cart]
      
    else 
      
      @cart = {}
      
    end
    
  end
  
  def add

    id = params[:id]

    if session[:cart] then
      
      cart = session[:cart]
      
    else
      
      session[:cart] = {}
      cart = session[:cart]
      
    end
    
    if cart[id] then
      
      cart[id] = cart[id] + 1
      
    else
      
      cart[id] = 1
      
    end
    
    redirect_to :action => :index
    
  end
  
  def remove

    id = params[:id]

    if session[:cart] then
      
      cart = session[:cart]
      
    else
      
      session[:cart] = {}
      cart = session[:cart]
      
    end
    
    if cart[id] then
      
      cart[id] = cart[id] - 1
      
      if cart[id] <= 0 then
        
        cart.delete(id)
        
      end
      
    end
    
    redirect_to :action => :index
    
  end
    
  def removeAll
    
    session[:cart] = nil
    redirect_to :action => :index
    
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<br>

<div class="container">
    
<% if @cart.empty? %>

    <div class="alert alert-info" role="alert"><b>Cart is empty.</b></div>
    
<% else %>

<% total = 0 %>

    <div class="panel panel-default">
        <div class="panel-body"><%= link_to(('<span class="glyphicon glyphicon-remove"></span> Remove all from Cart').html_safe, cart_clear_path, class: "btn btn-danger") %></div>
    </div>

    <table class="table">
        
        <thead>
            <tr>
                <th>Book title</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Actions</th>
            </tr>
        </thead>
        
        <tbody>
            
            <% @cart.each do |id,quantity | %>
            
                <% book = Book.find_by_id(id) %>
                
                <tr>
                    <td><%= link_to book.title, book %></td>
                    <td><%= number_to_currency(book.price, :unit => ('<span class="glyphicon glyphicon-eur"></span> ').html_safe) %></td>
                    <td><%= quantity %></td>
                    <td><%= number_to_currency(quantity * book.price, :unit => ('<span class="glyphicon glyphicon-eur"></span> ').html_safe) %></td>
                    <td>
                        <a href="/cart/<%= book.id %>" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-plus"></span></a>
                        <a href="/cart/remove/<%= book.id %>" class="btn btn-default btn-sm"><span class="glyphicon glyphicon-minus"></span></a>
                    </td>
                </tr>
                
                <% total += quantity * book.price %>
                
            <% end %>
            
            <tr class="well well-lg">
                <td colspan="3"><b>Total:</b> </td>
                <td class="lead"><%= number_to_currency(total, :unit => ('<span class="glyphicon glyphicon-eur"></span> ').html_safe) %></td>
                <td>&nbsp;</td>
            </tr>
        </tbody>
    
    </table>
    
    <div class="panel panel-default">
        <div class="panel-body"><%= link_to(('<span class="glyphicon glyphicon-ok"></span> <b>Checkout - Pay</b>').html_safe, new_charge_path, class: "btn btn-success") %></div>
    </div>

<% end %>

    <div class="panel panel-default">
        <div class="panel-body"><%= link_to(('<span class="glyphicon glyphicon-chevron-left"></span> Continue shopping').html_safe, { :controller => :books} , class: "btn btn-default") %></div>
    </div>

</div>