config/routes.rb
Rails.application.routes.draw do

  resources :books
  
  resources :charges, only: [:new, :create]
  
  devise_for :users, :controllers => { 
    
    :registrations => "user/registrations"
  }
  
  root 'pages#home'
  
  get '/about' => 'pages#about'
  
  get '/privacy' => 'pages#privacy'
  
  get '/terms_and_conditions' => 'pages#terms'
  
  get '/cart'  => 'cart#index'
  
  get 'cart/clear' => 'cart#removeAll'
  
  get 'cart/remove/:id' => 'cart#remove'

  get 'cart/:id' => 'cart#add'
  

end

app/models/book.rb
class Book < ActiveRecord::Base
    
    #Validation mainly based on regex.
    #As it is an active record sql injection is not possible for the functions provided by rails
    #The validation performed here also protects against html/javascript injection
    
    mount_uploader :picture, PictureUploader
    
    REGEX_TITLE = /\A^(:?[A-Za-z][\w\s\-\.\&\+]*[\w]){2,32}$\z/i
    
    REGEX_DESCRIPTION = /\A^[\w][\w\s\-\.\!\?\,\(\)\'\"\&\*\@\+\#]{3,256}$\z/i
    
    REGEX_CATEGORY = /\A^[A-Za-z][A-Za-z\s]{2,32}$\z/i
    
    REGEX_PRICE = /\A^[0-9]+(?:\.[0-9]+)?$\z/i
    
    validates :title,
    uniqueness: { case_sensitive: false },
    format: { with: REGEX_TITLE }
    
    validates :description,
    format: { with: REGEX_DESCRIPTION }
    
    validates :category,
    format: { with: REGEX_CATEGORY }
    
    validates :price, 
    format: { with: REGEX_PRICE }
    
    validate :picture_size

    private

    def picture_size

        if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
        end

    end
    
    def self.search(search)
        #Separate parameter is being used so SQL injection is not possible  
	    where("title LIKE ?", "%#{search}%")
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_filter :ensure_admin, :only => [:new, :edit, :destroy]

  #Check if the currently logged in user is Admin
  #if not an error will be returned
  def ensure_admin
    
    unless current_user && current_user.admin?
    
      render :text => "Access Error Message", :status => :unauthorized
      
    end
    
  end

  # GET /books
  # GET /books.json
  def index
    
    if params[:search]
      
	    @books = Book.search(params[:search]).order("id DESC")
	    
    else
      
	    @books = Book.all.order("id DESC")
	    
    end

  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :price, :picture, :category)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html => { multipart: true, :class => "form-horizontal book" } do |f| %>

  <% if @book.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, accept: 'image/png,image/jpeg' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>
  <div class="form-group">
    <%= f.label :category, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :category, :class => 'form-control' %>
    </div>
    <%=f.error_span(:category) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>

<div class="page-header">
  
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  
</div>

<%= form_tag(books_path, :method => "get", id: "search-form") do %>

  <span class="glyphicon glyphicon-search"></span>&nbsp;<%= text_field_tag :search, params[:search], placeholder: "Search by title" %>
  <%= submit_tag "Search", class: "btn btn-default" %>
  
<% end %>

<table class="table table-striped">
  
  <thead>
    
    <tr>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      
      <% if current_user && current_user.admin? %>
      
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        
      <% end %>
      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
    
  </thead>
  
  <tbody>
    
    <% @books.each do |book| %>
    
      <tr>
        <td><%= image_tag book.picture.url, size: "130x130" %></td>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.category %></td>
        <td><%= book.price %></td>
        
        <% if current_user && current_user.admin? %>
        
          <td><%=l book.created_at %></td>
          
        <% end %>
        
        <td>
          <% if current_user && current_user.admin? %>
          
            <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_book_path(book), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        book_path(book),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
                        
          <% elsif current_user %>
          
            <p><a href="/cart/<%= book.id %>"><span class="glyphicon glyphicon-plus"></span> Add to cart</a></p>
          
          <% end %>
          
        </td>
      </tr>
      
    <% end %>
    
  </tbody>
  
</table>

<% if current_user && current_user.admin? %>

  <%= link_to t('.new', :default => t("helpers.links.new")), new_book_path, :class => 'btn btn-primary' %>
  
<% end %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @book.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @book.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @book.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= image_tag(@book.picture.url, size: "350x350") if @book.picture? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @book.category %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>