config/routes.rb
Rails.application.routes.draw do

  resources :books
  
  resources :charges, only: [:new, :create]
  
  devise_for :users, :controllers => { 
    
    :registrations => "user/registrations"
  }
  
  root 'pages#home'
  
  get '/about' => 'pages#about'
  
  get '/privacy' => 'pages#privacy'
  
  get '/terms_and_conditions' => 'pages#terms'
  
  get '/cart'  => 'cart#index'
  
  get 'cart/clear' => 'cart#removeAll'
  
  get 'cart/remove/:id' => 'cart#remove'

  get 'cart/:id' => 'cart#add'
  

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    def new
        
        # Sum up the amount
        total = 0;
        
        session[:cart].each do |id,quantity |
            
            book = Book.find_by_id(id)
            total += quantity * book.price
            
        end
        
        #The amount is only used for displaying this time so multiplication is not required to cent format.
        @amountToDisplay = total
        
        #The amount has to be given in cents so multiplication is required
        #The system handles the amount for two decimal places
        
        if total > 0 then
            total *= 100;
        end
        
        @amount = total
    end
    
    def create
        
        if !session[:cart] || session[:cart].empty? then
            
            puts 'Payment failed. Cart is empty or session has been expired'
        
            render :new and return
            
        end
        
        # Build up the log message and sum up the amount
        logMessage = ""
        total = 0;
        
        session[:cart].each do |id,quantity |
            
            book = Book.find_by_id(id)
            
            if !logMessage.empty? then
                logMessage += ", "
            end
            
            logMessage += "Book title: " + book.title 
            logMessage += " - price: " + book.price.to_s + " EUR"
            logMessage += " - quantity: " + quantity.to_s + " piece(s)"
            
            total += quantity * book.price
            
        end
        
        #The amount has to be given in cents so multiplication is required
        #The system handles the amount for two decimal places
        
        if total > 0 then
            total *= 100;
        end
        
        @amount = total
    
        customer = Stripe::Customer.create(
            :email => params[:stripeEmail],
            :source  => params[:stripeToken]
        )
    
        charge = Stripe::Charge.create(
            :customer    => customer.id,
            :amount      => @amount.to_i,
            :description => 'NCI Ruby on Rails Stripe customer',
            :currency    => 'eur'
        )
        
        # Need to contruct and persist the custom payment object to track payments
        # Payment must contain the stripe token and be related to the user
        # This makes possible to track payments for users
        
        @payment = Payment.new({ 
            email: current_user.email,
            log_message: logMessage,
            token: params[:stripeToken], 
            user_id: current_user.id 
        })
        
        if !@payment.valid? then
            
            flash[:error] = "Please check registration errors" 
            puts 'Payment object is not valid'
            render :new and return
            
        end
        
        begin
        
            @payment.save
        
            rescue Exception => e
        
            flash[:error] = e.message
        
            puts 'Payment failed'
        
            render :new and return
        
        end
        
        flash[:success] = "Your payment was successful!"
        
        #empty the cart
        session[:cart] = nil
        @cart = nil
        
    end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="well well-lg">
    <h1>Thank you for your payment!</h1>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

<h1>Checkout</h1>
<h4>Please note this page is not a real payment page. It is part of a college project.</h4>

    <div class="well well-lg">

        <article>
            
            <label class="amount">
                <span>Amount:&nbsp;<span class="lead">
                    <%= number_to_currency(@amountToDisplay, :unit => ('<span class="glyphicon glyphicon-eur"></span> ').html_safe) %></span>
                </span>
            </label>
        
        </article>
    
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Book purchase"
              data-amount="<%= @amount %>"
              data-locale="auto"></script>
          
    </div>
          
    <div class="panel panel-default">
        <div class="panel-body"><%= link_to(('<span class="glyphicon glyphicon-chevron-left"> Back to your Cart').html_safe, cart_path, class: "btn btn-default") %></div>
    </div>
          
<% end %>