config/routes.rb
Rails.application.routes.draw do

  resources :books
  
  resources :charges, only: [:new, :create]
  
  devise_for :users, :controllers => { 
    
    :registrations => "user/registrations"
  }
  
  root 'pages#home'
  
  get '/about' => 'pages#about'
  
  get '/privacy' => 'pages#privacy'
  
  get '/terms_and_conditions' => 'pages#terms'
  
  get '/cart'  => 'cart#index'
  
  get 'cart/clear' => 'cart#removeAll'
  
  get 'cart/remove/:id' => 'cart#remove'

  get 'cart/:id' => 'cart#add'
  

end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
      <small>
          Copyright &copy; 2018 NCI Project
      </small>
      <nav>
          <ul>
              <li><%= link_to 'Terms & Conditions', terms_and_conditions_path %></li>
              <li><%= link_to 'Privacy', privacy_path %></li>
          </ul>
      </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-book"></span> Book Store NCI Project</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Books', books_path %></li>
        <li><%= link_to 'About', about_path %></li>
      </ul>
      
      <ul class="nav navbar-right">
        
        <% if current_user %>
        
          <li>
            <div class="col-xs-12">
                  <ul class="list-inline">
                    <li class="list-group-item"><%= link_to(('<span class="glyphicon glyphicon-user"></span> ' + current_user.email).html_safe,edit_user_registration_path, title: 'Edit Profile') %></li>
                    
                    <% if !current_user.admin? %>
                      
                      <li class="list-group-item">
                        
                        <% yourCartHTML = '<span class="glyphicon glyphicon-shopping-cart"></span> Go to Your Cart' %>
                        
                        <% if session[:cart] && session[:cart].size > 0 %>
                        
                          <% quantityCount = 0 %>
                          
                          <% session[:cart].each do |id, quantity | %>
                          
                            <% quantityCount += quantity %>
                            
                          <% end %>
                          
                          <% yourCartHTML += "&nbsp;<span class=\"badge badge-error\">#{quantityCount}</span>" %>
                          
                        <% end %>
                        
                        
                        <%= link_to((yourCartHTML).html_safe, cart_path) %>
                      </li>
                   
                    <% end %>
                   
                    <li class="list-group-item"><%= link_to(('<span class="glyphicon glyphicon-remove"></span> Logout').html_safe, destroy_user_session_path, class: 'btn-default', title: 'Logout', :method => :delete) %></li>
                  </ul>
            </div>
          </li>
          
        <% else %>
        
          <li><%= link_to(('<span class="glyphicon glyphicon-user"></span> Login / Sign Up').html_safe, new_user_session_path, class: 'btn btn-default', title: 'Login / Sign Up') %></li>
        
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Book Store</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <%= bootstrap_flash %>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>